[package]
name = "py_pi"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_pi"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
rand = "0.9.2"
